fix: temporary files not deleted, correctly check if files exist
kouprlabs/voltaserve pull request #158
Opened 2024-07-10 23:09 UTC by bouassaba

2024-07-10 23:14 UTC, bouassaba commented
This fixes #153 #154

2024-07-10 23:27 UTC, dsonck92 commented on api/router/file_router.go
>  				if err := os.Remove(path); err != nil {
I would suggest doing an `os.Remove` and ignoring `errors.Is(err, os.ErrNotExists)`, it's more atomic that way.

```go
if err := os.Remove(path); errors.Is(err, os.ErrNotExist) {
    return
} else if err != nil {
    log.GetLogger().Error(err)
}
```
No need for an extra `Stat` call either

2024-07-10 23:38 UTC, dsonck92 requested changes

2024-07-10 23:38 UTC, dsonck92 commented on webdav/main.go
> -	mu       sync.Mutex
You probably want to keep this mutex however, because concurrent map read/writes are undefined and racy. But maybe opt for an RWMutex since you might be reading more than you're writing.

The `go func()` can definitely trigger in parallel to the `basicAuthMiddleware` execution as the webserver is ran from `main()`.

2024-07-11 00:16 UTC, dsonck92 commented
I've also updated the PR comment to include the standardized `Closes: ` message so github will close the related issues.

2024-07-11 00:26 UTC, dsonck92 approved these changes

2024-07-11 00:30 UTC, merged