feat(language): lazy download for languages, and support more
kouprlabs/voltaserve pull request #169
Opened 2024-07-17 05:16 UTC by bouassaba

- Lazy download for spaCy language models in `language` service on an "on-demand" basis.
- Support more languages.

2024-07-17 20:58 UTC, loboda4450 requested changes

2024-07-17 20:58 UTC, loboda4450 commented on language/.flake8
This file is unnecessary, the flake8 configuration is done inside of pipeline

2024-07-17 22:26 UTC, bouassaba commented on language/.flake8
I added it for running the `flake8 .` command locally when I'm developing, I think it should be fine for this use-case?

2024-07-18 07:32 UTC, loboda4450 commented on language/.flake8
Yea, I will find out if workflow can make use of that file to avoid duplication.

2024-07-18 07:32 UTC, loboda4450 approved these changes

2024-07-18 19:20 UTC, dsonck92 approved these changes

2024-07-18 19:20 UTC, merged