feat: less docker layers
kouprlabs/voltaserve pull request #205
Opened 2024-07-22 18:36 UTC by loboda4450

Builds and rebuilds should be quicker.

Ref: https://docs.docker.com/build/cache/#minimize-the-number-of-layers

2024-07-22 20:44 UTC, bouassaba submitted a review, later dismissed

2024-07-22 21:24 UTC, dsonck92 requested changes

2024-07-22 21:24 UTC, dsonck92 commented on api/Dockerfile
In that case, we can completely remove the `go mod download` as `go build` should do that already.

2024-07-22 21:30 UTC, dsonck92 commented on api/Dockerfile
But, I think we're applying a "one size fits all" kinda assumption here. What I personally think would be more efficient is:

```Dockerfile
COPY go.mod go.sum .
RUN go mod download
COPY . .
RUN go build -o voltaserve-api
```

Locally, this would allow caching the `go mod download` based on the `go.mod` and `go.sum` contents.

2024-07-25 15:14 UTC, loboda4450 commented on api/Dockerfile
Yea, included in latest commit

2024-07-25 23:00 UTC, dsonck92 requested changes

2024-07-25 23:00 UTC, dsonck92 commented on ui/Dockerfile
> +    go build -o voltaserve-ui
And this one hasn't been altered

2024-07-25 23:00 UTC, dsonck92 commented on api/Dockerfile
I'm still missing the copy of the `go.mod` and `go.sum` files, now it won't have any effect.

2024-07-26 19:26 UTC, dsonck92 requested changes

2024-07-26 19:26 UTC, dsonck92 commented on ui/Dockerfile
>  COPY go.sum .
```suggestion
```

2024-07-26 19:33 UTC, dsonck92 approved these changes

2024-07-26 19:33 UTC, merged