fix(migration): make compatible with initial sql file
kouprlabs/voltaserve pull request #228
Opened 2024-07-26 17:27 UTC by dsonck92

2024-07-26 17:36 UTC, loboda4450 requested changes
Just as in another PR, less layers is better :D

2024-07-26 17:36 UTC, loboda4450 commented on migrations/Dockerfile
> +RUN cargo install cargo-build-dependencies
```suggestion
RUN cargo install cargo-build-dependencies &&\
        apk add --no-cache musl-dev
```

2024-07-26 17:36 UTC, loboda4450 commented on migrations/Dockerfile
> +RUN apk add --no-cache musl-dev
```suggestion

```

2024-07-26 19:18 UTC, dsonck92 commented on migrations/Dockerfile
> +RUN cargo install cargo-build-dependencies
I actually discovered that I could do it without this dependency at all :laughing:

2024-07-26 19:24 UTC, loboda4450 approved these changes
I like that

2024-07-27 10:33 UTC, loboda4450 approved these changes

2024-07-27 10:34 UTC, bouassaba submitted a review, later dismissed

2024-07-27 10:46 UTC, bouassaba submitted a review, later dismissed

2024-07-27 10:47 UTC, loboda4450 commented
@dsonck92 please alter the CI too then

2024-07-27 10:50 UTC, dsonck92 commented
> @dsonck92 please alter the CI too then

Yeah, just realized. I was a little misguided by the broken `main`, but I had this plan to move it to a "non -s" folder for some time already

2024-07-27 10:53 UTC, loboda4450 commented
Tbh migrations was lit imo, as idp, api etc. is ONE, but there will be multiple migrations

2024-07-27 17:02 UTC, loboda4450 approved these changes
That's pretty, but I'd personally have this bash script within workflow for clarity, but even without I like the outcome.

2024-07-27 17:20 UTC, dsonck92 commented
@loboda4450  Yeah, I'm not too pleased with the fact I had to introduce the bash script, I'd rather put it inside the Dockerfile itself. But I had some issues with getting the `case ... in` working. But I realize now that it could have been the lack of the `ARG` that I introduced after the build script.

2024-07-27 17:56 UTC, loboda4450 approved these changes

2024-07-27 18:16 UTC, merged