feat(ui): support keyboard shortcuts
kouprlabs/voltaserve pull request #230
Opened 2024-07-26 21:17 UTC by bouassaba

2024-07-26 22:13 UTC, Mrkazik99 requested changes

2024-07-26 22:13 UTC, Mrkazik99 commented on ui/src/components/file/file-menu.tsx
> +                        <Kbd>^</Kbd>+<Kbd>A</Kbd>
I believe "ctrl" should be here

2024-07-27 06:28 UTC, bouassaba commented on ui/src/components/file/file-menu.tsx
> +                        <Kbd>^</Kbd>+<Kbd>A</Kbd>
Yes! I had it non consistent, but, after changing it everywhere to `^` to represent `ctrl` key it kinda looks nice, see the Linux screenshot I uploaded in the description. What do you think?

2024-07-27 06:29 UTC, bouassaba commented on ui/src/components/file/file-menu.tsx
> +                        <Kbd>^</Kbd>+<Kbd>A</Kbd>
Because I believe everybody knows that `^` is control key.
It just looks shorter, the same for macOS, this `⌘` looks nicer than writing `command`.

2024-07-27 06:49 UTC, Mrkazik99 commented on ui/src/components/file/file-menu.tsx
> +                        <Kbd>^</Kbd>+<Kbd>A</Kbd>
Yes in case of more advanced users, this would be okay
But let's consider some scenario
"Your Mother asks You to help her sister (your aunt) with phone that is overwhelmed because of amount of photos on it, so You decided to provide her an easy access to voltaserve on phone. Everything is fine, but finally she has discovered that voltaserve also is accessible on her old i3-4th gen laptop".
She will be able to understand that ctrl=ctrl on her keyboard, but in case shortcut will be ^+a, this will be not obvious for her.

2024-07-27 06:50 UTC, loboda4450 commented on ui/src/components/file/file-menu.tsx
> +                        <Kbd>^</Kbd>+<Kbd>A</Kbd>
Yup, that is a scenario noone thinks about but DOES its job. I vote for that change.

2024-07-27 10:15 UTC, Mrkazik99 requested changes

2024-07-27 10:15 UTC, Mrkazik99 commented on ui/src/components/file/list/index.tsx
> +        (keyName === 'command+backspace' && isMacOS()) ||
Based on screens and Kbd components I think it should be command+delete, correct me if I'm wrong cause I've never used Mac

2024-07-27 10:15 UTC, Mrkazik99 commented on ui/src/components/file/file-menu.tsx
> +                      <Kbd>⌘</Kbd>+<Kbd>delete</Kbd>
Do we really need separate shortcut for mac here?

2024-07-27 10:26 UTC, loboda4450 approved these changes

2024-07-27 10:26 UTC, dsonck92 commented on ui/src/components/file/file-menu.tsx
> +                      <Kbd>⌘</Kbd>+<Kbd>delete</Kbd>
I think this is because there's no delete button on mac, and this is the keyboard shortcut used by Finder

2024-07-27 10:27 UTC, bouassaba commented on ui/src/components/file/file-menu.tsx
> +                      <Kbd>⌘</Kbd>+<Kbd>delete</Kbd>
Mac does't have a `Del` key lol, so Mac users are used to `⌘+delete`, unlike PC users who are used to `Del`.

2024-07-27 10:28 UTC, bouassaba commented on ui/src/components/file/list/index.tsx
> +        (keyName === 'command+backspace' && isMacOS()) ||
"backspace" and "delete" are the same thing on Mac.

2024-07-27 10:46 UTC, Mrkazik99 approved these changes

2024-07-27 10:46 UTC, merged