Initial version of Cloud Console and IDP modified for Cloud Console
kouprlabs/voltaserve pull request #298
Opened 2024-09-03 21:00 UTC by Mrkazik99

Closes: #151

2024-09-03 21:11 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const suspendUser = async (
Let's do a `useCallback()` here to avoid having this function recreated on each render.

2024-09-03 21:11 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const makeAdminUser = async (
Let's do a `useCallback()` here to avoid having this function recreated on each render.

2024-09-03 21:11 UTC, bouassaba commented on ui/src/pages/console/console-panel-workspaces.tsx
> +  const renameWorkspace = async (
Let's do a `useCallback()` here to avoid having this function recreated on each render.

2024-09-03 21:12 UTC, bouassaba commented on ui/src/pages/console/console-panel-workspaces.tsx
> +                              {/*<MenuItem>Change quota</MenuItem>*/}
Please remove commented code.

2024-09-03 21:14 UTC, bouassaba commented on ui/src/pages/console/console-panel-organizations.tsx
> +          <div> No organizations found </div>
Please remove the blanks around the text, if you need a padding use padding classes with Tailwind CSS.

2024-09-03 21:15 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +  const changeInvitationStatus = async (
Let's do a `useCallback()` here to avoid having this function recreated on each render.

2024-09-03 21:15 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +                                {/*<MenuItem*/}
Please remove commented code.

2024-09-03 21:16 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +          <div> No invitations found </div>
Please remove the blanks around the text, if you need a padding use padding classes with Tailwind CSS.

2024-09-03 21:16 UTC, bouassaba commented on ui/src/pages/console/console-panel-groups.tsx
> +          <div> No groups found </div>
Please remove the blanks around the text, if you need a padding use padding classes with Tailwind CSS.

2024-09-03 21:16 UTC, bouassaba commented on ui/src/pages/console/console-panel-database-overview.tsx
> +  // const [socket, setWebsocket] = useState<WebSocket>(new WebSocket('ws://192.168.1.254:20002'))
Please remove commented code.

2024-09-03 21:17 UTC, bouassaba commented on ui/src/pages/console/console-panel-database-indexes.tsx
> +      console.log('Fatal error while dispatching rebuild index', indexname)
If this is meant to be an error, please use `console.error()` instead.

2024-09-03 21:19 UTC, bouassaba commented on ui/src/infra/token.ts
> +    return JSON.parse(atob(accessToken.split('.')[1])).sub
It's better to use the JWT library to extract the `sub` instead of using string manipulation.

2024-09-03 21:19 UTC, bouassaba commented on ui/src/infra/token.ts
> +    return JSON.parse(atob(accessToken.split('.')[1])).is_admin
It's better to use the JWT library to extract the `is_admin` claim, instead of using string manipulation.

2024-09-03 21:20 UTC, bouassaba commented on ui/src/components/console/deadmin-button.tsx
> +const DeAdminButton = () => {
What is the meaning of "deadmin"?

2024-09-03 21:26 UTC, bouassaba commented on ui/config/config.go
> +	config.ConsoleUrl = os.Getenv("CONSOLE_URL")
Please rename `config.ConsoleUrl` to `config.ConsoleURL` to be consistent.

2024-09-03 21:26 UTC, bouassaba commented on ui/config/types.go
> +	ConsoleUrl string
Please rename `ConsoleUrl` to `ConsoleURL` to be consistent.

2024-09-03 21:31 UTC, bouassaba commented on ui/src/components/app-bar/app-bar-search.tsx
> +          navigate(`/console/users?q=${encodeQuery(value)}`)
What about using `URLSearchParams` API to build the search query parameters instead of building it manually with string interpolation.
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams

2024-09-03 21:38 UTC, bouassaba commented on ui/src/pages/console/console-panel-database-indexes.tsx
> +    indexname: string | null,
Please rename indexname to indexName to be camel case.

2024-09-03 21:40 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +  const [actionState, setActionState] = useState<boolean | undefined>(undefined)
No need to do `useState<boolean | undefined>(undefined)`.
This is enough `useState<boolean>()`, and has the same semantics.

2024-09-03 21:40 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +  const [invitationId, setInvitationId] = useState<string | undefined>(
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-03 21:40 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +  const [list, setList] = useState<InvitationManagementList | undefined>(
No need to do `useState< InvitationManagementList | undefined>(undefined)`.
This is enough `useState< InvitationManagementList >()`, and has the same semantics.

2024-09-03 21:41 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +  const [confirmWindowAction, setConfirmWindowAction] = useState<
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-03 21:44 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +            totalPages={Math.ceil(list.totalElements / size)}
You don't need `Math.ceil()` here, because `totalElement` will never be a floating number.

2024-09-03 21:45 UTC, loboda4450 commented on ui/src/pages/console/console-panel-database-indexes.tsx
> +    indexname: string | null,
This one needs adjustment also on API side. And you just probably made me realize that I might have potentially created a SQLInjection on API side. Gotta check on that tomorrow.

2024-09-03 21:45 UTC, bouassaba commented on ui/src/client/console/console.ts
> +export type IndexManagement = {
Please name these with camel case:
```typescript
export type IndexManagement = {
  tableName: string
  indexName: string
  indexDef: string
}
```

2024-09-03 21:46 UTC, loboda4450 commented on ui/src/client/console/console.ts
> +export type IndexManagement = {
This one needs adjustment also on API side too.

2024-09-03 21:48 UTC, bouassaba commented on ui/src/pages/console/console-panel-organization.tsx
> +  const [organizationData, setOrganizationData] = useState<
No need to do `useState<OrganizationManagement | undefined>(undefined)`.
This is enough `useState<OrganizationManagement>()`, and has the same semantics.

2024-09-03 21:48 UTC, bouassaba commented on ui/src/pages/console/console-panel-organization.tsx
> +  const [usersData, setUsersData] = useState<
No need to do `useState<UserOrganizationManagementList | undefined>(undefined)`.
This is enough `useState<UserOrganizationManagementList>()`, and has the same semantics.

2024-09-03 21:48 UTC, loboda4450 commented on ui/src/components/console/deadmin-button.tsx
> +const DeAdminButton = () => {
It was a joke, you know, DeAdmin - DeadMin XD

2024-09-03 21:48 UTC, bouassaba commented on ui/src/pages/console/console-panel-organization.tsx
> +  const [workspacesData, setWorkspacesData] = useState<
No need to do `useState<WorkspaceManagementList | undefined>(undefined)`.
This is enough `useState<WorkspaceManagementList>()`, and has the same semantics.

2024-09-03 21:48 UTC, bouassaba commented on ui/src/pages/console/console-panel-organization.tsx
> +  const [groupsData, setGroupsData] = useState<GroupManagementList | undefined>(
No need to do `useState<GroupManagementList | undefined>(undefined)`.
This is enough `useState<GroupManagementList >()`, and has the same semantics.

2024-09-03 21:54 UTC, bouassaba commented on ui/src/pages/console/console-panel-organization.tsx
> +      ConsoleApi.getOrganizationById({ id: id }).then((value) => {
I suggest to create a function that used `async/await` for a more concise syntax:
```typescript
let organization = await ConsoleApi.getOrganizationById({ id: id })
setOrganizationData(organization)

let users = await ConsoleApi.getUsersByOrganization({
  id: id,
  page: usersPage,
  size: 5,
})
setUsersData(users)

let workspaces = await ConsoleApi.getWorkspacesByOrganization({
  id: id,
  page: workspacesPage,
  size: 5,
})
setWorkspacesData(workspaces)

let groups = await ConsoleApi.getGroupsByOrganization({
  id: id,
  page: workspacesPage,
  size: 5,
})
setGroupsData(groups)
```

Also notice that:
```typescript
ConsoleApi.getOrganizationById({ id: id })
```
Can be simplified as:
```typescript
ConsoleApi.getOrganizationById({ id })
```

2024-09-03 21:58 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  useEffect(() => {
Please here as well create an `async` function that uses `async/await` syntax and call it inside `useEffect()`.

2024-09-03 21:58 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  useEffect(() => {
Please here as well create an async function that uses async/await syntax and call it inside useEffect().

2024-09-03 21:58 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  useEffect(() => {
Please here as well create an async function that uses async/await syntax and call it inside useEffect().

2024-09-03 21:59 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  useEffect(() => {
Please here as well create an async function that uses `async/await` syntax and call it inside `useEffect()`.

2024-09-03 22:00 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +                  disableLastNav
In React, it's more preferable to do `disableLastNav={true}`, unlike Angular.

2024-09-03 22:00 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +                  disableMiddleNav
In React, it's more preferable to do `disableMiddleNav ={true}`, unlike Angular.

2024-09-03 22:02 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const [list, setList] = useState<ConsoleUsersResponse | undefined>(undefined)
No need to do `useState<ConsoleUsersResponse | undefined>(undefined)`.
This is enough `useState<ConsoleUsersResponse >()`, and has the same semantics.

2024-09-03 22:03 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const [userId, setUserId] = useState<string | undefined>(undefined)
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-03 22:03 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const [userEmail, setUserEmail] = useState<string | undefined>(undefined)
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-03 22:03 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const [actionState, setActionState] = useState<boolean | undefined>(undefined)
No need to do `useState<boolean | undefined>(undefined)`.
This is enough `useState<boolean>()`, and has the same semantics.

2024-09-03 22:04 UTC, bouassaba commented on ui/src/pages/console/console-panel-users.tsx
> +  const [confirmWindowAction, setConfirmWindowAction] = useState<
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-03 22:06 UTC, bouassaba commented on ui/src/pages/console/console-panel-workspaces.tsx
> +          <div> No workspaces found </div>
Please remove the blanks around the text, if you need a padding use padding classes with Tailwind CSS.

2024-09-03 22:08 UTC, bouassaba commented on api/router/version_router.go
> +// GetVersion godoc
Did you run `swag fmt` to format Swag comments?

2024-09-03 22:10 UTC, bouassaba commented on idp/package.json
> +    "meilisearch": "^0.40.0",
Please let's not do `^` because NPM packages tend to push broken minor versions, and the project may not build in the future. Please use fixed versions, in this case `0.40.0`

2024-09-03 22:14 UTC, bouassaba commented on idp/src/health/router.ts
> +router.get('', async (_: Request, res: Response, next: NextFunction) => {
Let's do a slash here `'/'` it's not common in routing to keep an empty string `''`.

2024-09-03 22:17 UTC, bouassaba commented on idp/src/user/repo.ts
> +  private mapList(list: any): User[] {
I don't think it's a good idea to do `any` here, specially this is backend code, let's type it.

2024-09-03 22:18 UTC, bouassaba commented on idp/src/user/router.ts
> +// ---------- Admin Part -------------
I think this comment can go away, as we are not consistent doing such division everywhere.

2024-09-03 22:22 UTC, bouassaba commented on idp/src/user/router.ts
> +  '/by_id',
`'/by_id'`  is not very RESTful, let's do `/:id`.

2024-09-03 22:23 UTC, bouassaba commented on idp/src/user/service.ts
> +import {getConfig} from '@/config/config'
Most of these imports need to be formatted, please run `npm run format`, notice the missing spaces around the symbols.

2024-09-03 22:23 UTC, bouassaba commented on idp/src/user/service.ts
> +    return {data: await userRepo.listAllByIds(users.data.map((value) => {return value.id})), totalElements: users.totalElements, size: size, page: page}
These lines are super long, I'm pretty sure you forgot to format the code.

2024-09-03 22:25 UTC, bouassaba requested changes
Please check the review comments.

2024-09-04 08:10 UTC, loboda4450 commented on ui/src/pages/console/console-panel-database-indexes.tsx
> +    indexname: string | null,
Nah, API is protected from SQLInjection.

2024-09-04 16:24 UTC, Mrkazik99 commented on ui/src/components/app-bar/app-bar-search.tsx
> +          navigate(`/console/users?q=${encodeQuery(value)}`)
I've extended your serachbar to not break existing look and existing search veiws

2024-09-04 16:32 UTC, bouassaba commented on ui/src/components/app-bar/app-bar-search.tsx
> +          navigate(`/console/users?q=${encodeQuery(value)}`)
Sure, I was talking only about the manual string concatenation: `?q=${}`, where I suggested to improve it by using `URLSearchParams `.

2024-09-04 16:34 UTC, bouassaba commented on ui/src/components/app-bar/app-bar-search.tsx
> +          navigate(`/console/users?q=${encodeQuery(value)}`)
I'm aware that it was like that before, I just suggested to improve it, because the code grows already, but that's not a big deal, we can do it in the future.

2024-09-04 16:39 UTC, Mrkazik99 commented on ui/src/pages/console/console-panel-invitations.tsx
> +            totalPages={Math.ceil(list.totalElements / size)}
But (totalElements / size) might be floating number
6/5 = 1.2 Which means we have 1.2 of page here to display
if We would use parseInt it would cut the decimal part and leave only 1 page, which means if We have 6 users 5 of them are visible on pagination and one is inaccessible
If I use Math.ceil it will always round my float to the bigger one, which means if there is 1.2 of page to display it will display 2 pages

2024-09-04 16:42 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +            totalPages={Math.ceil(list.totalElements / size)}
Ah I see, but why you don't use `list.totalPages` that comes from the API?

2024-09-04 16:48 UTC, bouassaba commented on idp/src/health/router.ts
> +router.get('', async (_: Request, res: Response, next: NextFunction) => {
Okay

2024-09-04 16:54 UTC, bouassaba commented on ui/src/pages/console/console-panel-workspaces.tsx
> +  const [currentName, setCurrentName] = useState<string | undefined>(undefined)
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-04 16:54 UTC, bouassaba commented on ui/src/pages/console/console-panel-workspaces.tsx
> +  const [workspaceId, setWorkspaceId] = useState<string | undefined>(undefined)
No need to do `useState<string | undefined>(undefined)`.
This is enough `useState<string>()`, and has the same semantics.

2024-09-04 16:55 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  const [userData, setUserData] = useState<ConsoleUser | undefined>(undefined)
No need to do `useState<ConsoleUser | undefined>(undefined)`.
This is enough `useState<ConsoleUser>()`, and has the same semantics.

2024-09-04 16:55 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  const [organizationsData, setOrganizationsData] = useState<
No need to do `useState<OrganizationUserManagementList | undefined>(undefined)`.
This is enough `useState<OrganizationUserManagementList>()`, and has the same semantics.

2024-09-04 16:55 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  const [workspacesData, setWorkspacesData] = useState<
No need to do `useState<WorkspaceUserManagementList | undefined>(undefined)`.
This is enough `useState<WorkspaceUserManagementList>()`, and has the same semantics.

2024-09-04 16:55 UTC, bouassaba commented on ui/src/pages/console/console-panel-user.tsx
> +  const [groupsData, setGroupsData] = useState<
No need to do `useState<GroupUserManagementList | undefined>(undefined)`.
This is enough `useState<GroupUserManagementList>()`, and has the same semantics.

2024-09-04 17:57 UTC, Mrkazik99 commented on ui/src/pages/console/console-panel-user.tsx
> +                  disableLastNav
![image](https://github.com/user-attachments/assets/72885025-38a8-4969-8953-948f1d462483)
I've always seen in documentation to use only name of property if it is static true/false, above example is from chakra docs and below is another example from MUI docs 
![image](https://github.com/user-attachments/assets/8c153f43-ff5d-4bc6-be9b-699f43395add)

2024-09-04 17:57 UTC, Mrkazik99 commented on ui/src/pages/console/console-panel-user.tsx
> +                  disableMiddleNav
As previous comment

2024-09-04 18:00 UTC, Mrkazik99 commented on idp/src/user/repo.ts
> +  private mapList(list: any): User[] {
I've done it exactly like there https://github.com/kouprlabs/voltaserve/blob/main/idp/src/user/repo.ts#L237

2024-09-04 18:02 UTC, bouassaba commented on idp/src/user/repo.ts
> +  private mapList(list: any): User[] {
Right, I was wondering if we can improve it easily? I guess let's do it in the future, not now.

2024-09-04 18:19 UTC, Mrkazik99 commented on ui/src/pages/console/console-panel-invitations.tsx
> +            totalPages={Math.ceil(list.totalElements / size)}
Those reqeusts come from Console API, and in console we do not provide totalPages (one operation less on console API)

2024-09-04 18:21 UTC, bouassaba commented on ui/src/pages/console/console-panel-invitations.tsx
> +            totalPages={Math.ceil(list.totalElements / size)}
Ah right, then it's fine, we can live with `Math.ceil()` 😄

2024-09-04 19:30 UTC, bouassaba approved these changes

2024-09-04 19:55 UTC, loboda4450 approved these changes

2024-09-04 19:58 UTC, merged

2024-09-05 10:02 UTC, dsonck92 commented on migrations/src/m20240718_000001_create_user.rs
> +                    )
**Never** change existing migrations. This needs to be reverted asap