feat(migrations): Add field in user to handle force change password
kouprlabs/voltaserve pull request #323
Opened 2024-09-11 06:35 UTC by Mrkazik99

2024-09-11 07:03 UTC, loboda4450 requested changes

2024-09-11 07:03 UTC, loboda4450 commented on migrations/src/lib.rs
> +            Box::new(m20240907_000001_add_user_forcechangepassword_field::Migration),
Tbh I do not like forcechangepassword, underscored would be preferred as it would be the same as in database.

2024-09-11 15:49 UTC, Mrkazik99 commented on migrations/src/lib.rs
> +            Box::new(m20240907_000001_add_user_forcechangepassword_field::Migration),
I've done it exactly like it was there https://github.com/kouprlabs/voltaserve/blob/feat/migration-user-manipulation/migrations/src/lib.rs#L25

2024-09-11 15:53 UTC, bouassaba commented on migrations/src/lib.rs
> +            Box::new(m20240907_000001_add_user_forcechangepassword_field::Migration),
@Mrkazik99 in the example you pointed `userpermission` is a table.
In our current example `forcechangepassword` is a field, therefore it needs to be `force_change_password`.

The rule in the DB side being:
Is it a connection table the connects apple with orange? then it should be `apple_orange`.
Is it a simple table? then it's lower case without underscore: `goodbreakfasts`.
Is it a field? always snake case: `eat_non_stop`.

2024-09-13 05:34 UTC, loboda4450 approved these changes

2024-09-13 05:35 UTC, merged